// user
export const SIGN_IN = "SIGN_IN"
export const SIGN_OUT = "SIGN_OUT"


//app settings
export const SIDE_BAR = "SIDE_BAR"
export const ALL_PACKAGE_GET_STATUS_TRUE = "ALL_PACKAGE_GET_STATUS_TRUE";
export const ALL_PACKAGE_GET_STATUS_FALSE = "ALL_PACKAGE_GET_STATUS_FALSE";
export const FEATURE_LIST_GET_STATUS_TRUE = "FEATURE_LIST_GET_STATUS_TRUE";
export const FEATURE_LIST_GET_STATUS_FALSE = "FEATURE_LIST_GET_STATUS_FALSE";

// reusbaleinfo
export const PACKAGE_UPDATE_TRUE = 'PACKAGE_UPDATE_TRUE'
export const PACKAGE_UPDATE_FALSE = 'PACKAGE_UPDATE_FALSE'
export const PACKAGE_UPDATE = 'PACKAGE_UPDATE'
export const SHIFT_UPDATE_TRUE = 'SHIFT_UPDATE_TRUE'
export const SHIFT_UPDATE_FALSE = 'SHIFT_UPDATE_FALSE'
export const SHIFT_UPDATE = 'SHIFT_UPDATE'
export const TRAINING_TYPE_UPDATE = 'TRAINING_TYPE_UPDATE'
export const TRAINING_TYPE_UPDATE_TRUE = 'TRAINING_TYPE_UPDATE_TRUE'
export const TRAINING_TYPE_UPDATE_FALSE = 'TRAINING_TYPE_UPDATE_FALSE'


// Alert-success
export const ALERT_SHOW = 'ALERT_SHOW'
export const SUCCESS_SHOW = 'SUCCESS_SHOW'
export const ALERT_HIDE = 'ALERT_HIDE'
export const SUCCESS_HIDE = 'SUCCESS_HIDE'